In [3]:
import numpy as np
import pandas as pd
from math import sqrt
import scipy
from scipy import linalg

In [60]:
def SVD(A):
    print(A)
    AT = A.transpose()
    AdotAT = A.dot(AT)
    ATdotA = AT.dot(A)            
    λ, V = linalg.eig(ATdotA)
    print(λ)
    VT = V.transpose()
    for i in range(len(λ)):
        λ[i] = sqrt(abs(λ[i]))
    λ = sorted(λ, reverse = True)
    S = np.diag(λ)
    S_inversed = np.linalg.inv(S)    
    #print(S)
    #print(S_inversed)
    #print(V)
    for i in range(len(V)):
        print(V[:,i])
    U = A.dot(V.dot(S_inversed))    
    #print(U[:,0])
    u, s, v = np.linalg.svd(A)
    print("-------------")
    print(U)
    print(S)
    print(V)
    print("-------------")
    print(u)
    print(s)
    print(v)          
    print("-------------")
    print(A)
    print(U.dot(S.dot(VT)))
    return 0

In [61]:
A = np.array([[0, 1, 1], [sqrt(2), 2, 0], [0, 1, 1]])
#A = np.array([[0, sqrt(2), 0], [1, 2, 1], [1, 0, 1]])
SVD(A)

[[0.         1.         1.        ]
 [1.41421356 2.         0.        ]
 [0.         1.         1.        ]]
[ 8.00000000e+00+0.j -7.68216532e-18+0.j  2.00000000e+00+0.j]
[-0.40824829 -0.8660254  -0.28867513]
[ 0.70710678 -0.5         0.5       ]
[-5.77350269e-01 -7.84321844e-17  8.16496581e-01]
-------------
[[-4.08248290e-01+0.j -5.55111512e-17+0.j  2.94586300e+08+0.j]
 [-8.16496581e-01+0.j  1.11022302e-16+0.j -2.94586300e+08+0.j]
 [-4.08248290e-01+0.j -5.55111512e-17+0.j  2.94586300e+08+0.j]]
[[2.82842712e+00+0.j 0.00000000e+00+0.j 0.00000000e+00+0.j]
 [0.00000000e+00+0.j 1.41421356e+00+0.j 0.00000000e+00+0.j]
 [0.00000000e+00+0.j 0.00000000e+00+0.j 2.77167193e-09+0.j]]
[[-4.08248290e-01  7.07106781e-01 -5.77350269e-01]
 [-8.66025404e-01 -5.00000000e-01 -7.84321844e-17]
 [-2.88675135e-01  5.00000000e-01  8.16496581e-01]]
-------------
[[-0.40824829  0.57735027 -0.70710678]
 [-0.81649658 -0.57735027  0.        ]
 [-0.40824829  0.57735027  0.70710678]]
[2.82842712e+00 1.41421356e+00 2

0